ALTER TABLE tbl_dota_player_matches
    ADD COLUMN IF NOT EXISTS gold_per_min INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS xp_per_min INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_hits INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hero_damage INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tower_damage INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hero_healing INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS average_rank INTEGER,
    ADD COLUMN IF NOT EXISTS party_size INTEGER,
    ADD COLUMN IF NOT EXISTS game_mode INTEGER NOT NULL DEFAULT 0;
